[workspace]
resolver = "2"

members = [
  "apps",
  "matchmaker/mm_template",
  "matchmaker/mm_token_exch",
  "proof_of_stake",
  "shared",
  "tests",
  "tx_prelude",
  "vm_env",
  "macros",
  "vp_prelude",
  "wasm_leak",
]

# wasm packages have to be built separately
exclude = [
  "wasm",
  "wasm_for_tests",
]

[patch.crates-io]
tracing = {git = "https://github.com/tokio-rs/tracing/", rev = "6cc6c47354ceeb47da7c95faa41c6d29b71b5f37"}
tracing-core = {git = "https://github.com/tokio-rs/tracing/", rev = "6cc6c47354ceeb47da7c95faa41c6d29b71b5f37"}
tracing-subscriber = {git = "https://github.com/tokio-rs/tracing/", rev = "6cc6c47354ceeb47da7c95faa41c6d29b71b5f37"}
# TODO backported patch in the noise protocl for <https://github.com/libp2p/rust-libp2p/pull/2264>, blocked on libp2p upgrade <https://github.com/anoma/anoma/pull/751>
libp2p = {git = "https://github.com/heliaxdev/rust-libp2p.git", rev = "1abe349c231eb307d3dbe03f3ffffc6cf5e9084d"}

[profile.release]
lto = true
opt-level = 3
panic = "unwind"
