[package]
name = "wasm_leak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anoma = {path = "../shared", features = ["testing", "wasm-runtime"]}
borsh = "0.9.0"